---

- name: "Install UFW"
  apt:
    name: ufw

- name: "Ensure UFW allows SSH"
  ufw:
    to_port: "22"
    proto: "tcp"
    rule: "allow"
    comment: "OpenSSH"

- name: "Ensure UFW is enabled and denies by default"
  ufw:
    state: "enabled"
    policy: "deny"
    direction: "incoming"
