---

- name: "Apply roles common to all servers"
  hosts: all
  roles:
    - ufw
    - wireguard
    - node_exporter

- name: "Apply roles specific to monitor servers"
  hosts: monitors
  roles:
    - prometheus-server
